logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: log/practical-java.log
server:
   port : 8001

spring:
  jackson:
    property-naming-strategy : SNAKE_CASE

#springdoc:
#  swagger-ui:
 #   supported-submit-methods:
#      - get

management:
    metrics:
      export:
        elastic:
          step: 30s
          host: http://localhost:9200

